version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    # ports:
    #   - 8081:${CLIENT_PORT}
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - nginx-net
  backend:
    build:
      context: backend
      dockerfile: dev.Dockerfile
    environment:
      MONGO_HOST: mongodb
    volumes:
      - ./backend:/usr/src/app
      - /app/node_modules
    networks:
      - mongodb-net
      - nginx-net
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.mnt/mongo:/var/lib/mongodb/data
    networks:
      - mongodb-net
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: nginx
      dockerfile: dev.Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./.mnt/nginx/logs:/var/log/nginx/
    networks:
      - nginx-net
networks:
  mongodb-net:
    driver: bridge
  nginx-net:
    driver: bridge
