version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - nginx-net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      MONGO_HOST: mongodb
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /app/node_modules
    networks:
      - mongodb-net
      - nginx-net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.mnt/mongo:/var/lib/mongodb/data
    networks:
      - mongodb-net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./.mnt/nginx/logs:/var/log/nginx/
    networks:
      - nginx-net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
networks:
  mongodb-net:
    driver: bridge
  nginx-net:
    driver: bridge
