version: '3.8'
services:
  frontend:
    extends:
      file: docker-compose/common.yml
      service: frontend
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8081:5173
    environment:
      MODE: 'development'
    volumes:
      - ./frontend:/usr/src/app
  backend:
    extends:
      file: docker-compose/common.yml
      service: backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8080:3000
    volumes:
      - /app/node_modules
      - ./backend:/usr/src/app:delegated
    environment:
      MODE: 'development'
  mongodb:
    extends:
      file: docker-compose/common.yml
      service: mongodb
    ports:
      - 27017:27017
  nginx:
    extends:
      file: docker-compose/common.yml
      service: nginx
