version: '3.8'
services:
  frontend:
    extends:
      file: app.compose.yml
      service: frontend
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - 8081:5173
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    extends:
      file: app.compose.yml
      service: backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    ports:
      - 8080:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    extends:
      file: app.compose.yml
      service: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
    extends:
      file: app.compose.yml
      service: nginx
