version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
  backend:
    extends:
      file: app.compose.yml
      service: backend
    build:
      context: backend
      dockerfile: prod.Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
  mongodb:
    extends:
      file: app.compose.yml
      service: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
  nginx:
    extends:
      file: app.compose.yml
      service: nginx
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 20M
